### ISSUE TITLE
[Feat]: 블루그린 배포 적용

### ISSUE THREAD

**Issue by nohy6630** [Team-NumberOne/Backend#98]
**Issue**
- 이슈 내용: 블루그린 배포 적용

**Branch Name**
- 생성 브랜치 이름 : `feat/bluegreen`

**To-Do List**
- [x] ec2 docker-compose.yml 수정
- [x] ec2 쉘스크립트 추가
- [x] 배포 yml 수정
